config/routes.rb
Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'

  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bird.rb
class Bird < Pet
end

app/models/cat.rb
class Cat < Pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :pet_owner

  validates :name, presence: true
end

app/models/pet_owner.rb
class PetOwner < ApplicationRecord
  has_many :pets # this is an STI relationship
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motoradminpoc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
    .header {
      display: flex;
      justify-content: center;
      width: 100%;
    }
    </style>
  </head>

  <body>
    <div class="header">
      <%= link_to 'Admin', motor_admin_path %>
    </div>

    <%= yield %>
  </body>
</html>